import dotenv from 'dotenv';
import mongoose from 'mongoose';
import Register from '../models/Register.js';
import Role from '../models/Role.js';
import dbConnect from '../config/db.js';
import { seedRolesAndPermissions } from './seedRolesPermissions.js';

// Load environment variables
dotenv.config();

/**
 * System Initialization Script
 * - Seeds roles and permissions if none exist
 * - Creates first Super Admin account if no users exist
 * - Ensures system has at least one Super Admin at all times
 */

async function initializeSystem() {
    try {
        console.log('🚀 Starting system initialization...\n');

        // Step 1: Check and seed roles/permissions
        const roleCount = await Role.countDocuments();
        if (roleCount === 0) {
            console.log('📝 No roles found. Seeding roles and permissions...');
            await seedRolesAndPermissions();
            console.log('');
        } else {
            console.log(`✓ Found ${roleCount} existing roles`);
        }

        // Step 2: Get Super Admin role
        const superAdminRole = await Role.findOne({ name: 'Super Admin' });
        if (!superAdminRole) {
            throw new Error('Super Admin role not found! Please run seeder first.');
        }

        // Step 3: Check for existing users
        const userCount = await Register.countDocuments();
        console.log(`📊 Current user count: ${userCount}`);

        if (userCount === 0) {
            console.log('\n👤 No users found. Creating default Super Admin account...\n');
            
            const defaultSuperAdmin = await Register.create({
                name: 'System Administrator',
                email: 'hussali817817@gmail.com',
                phone: '+1234567890',
                password: 'Admin@123',
                plainPassword: 'Admin@123',
                isAutoGeneratedPassword: false,
                roles: [superAdminRole._id],
                status: 'Active',
                address: 'System',
                city: 'System',
                agentOTP: null,
                agentOTPExpiry: null,
                adminOTP: null,
                adminOTPExpiry: null
            });
        } else {
            // Step 4: Ensure at least one Super Admin exists
            const superAdminCount = await Register.countDocuments({ 
                roles: superAdminRole._id 
            });

            if (superAdminCount === 0) {
                console.log('\n⚠️  WARNING: No Super Admin found in system!');
                console.log('Converting first user to Super Admin...\n');

                const firstUser = await Register.findOne().sort({ createdAt: 1 });
                if (firstUser) {
                    firstUser.roles = [superAdminRole._id];
                    await firstUser.save();
                    
                    console.log(`✅ User "${firstUser.name}" (${firstUser.email}) promoted to Super Admin`);
                }
            } else {
                console.log(`✓ Found ${superAdminCount} Super Admin(s) in system`);
            }
        }

        console.log('\n✅ System initialization completed successfully!\n');

    } catch (error) {
        console.error('❌ System initialization failed:', error);
        throw error;
    }
}

// Run initialization if executed directly
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);
const isMainModule = process.argv[1] === __filename || process.argv[1].replace(/\\/g, '/').endsWith('initializeSystem.js');

if (isMainModule) {
    dbConnect()
        .then(() => initializeSystem())
        .then(() => {
            console.log('✅ Initialization complete. Exiting...');
            process.exit(0);
        })
        .catch((error) => {
            console.error('❌ Initialization failed:', error);
            process.exit(1);
        });
}

export default initializeSystem;
