import dotenv from 'dotenv';
import bcrypt from 'bcrypt';
import mongoose from 'mongoose';
import Register from '../models/Register.js';
import dbConnect from '../config/db.js';

// Load environment variables
dotenv.config();

/**
 * Reset Super Admin Password
 * 
 * This script resets the Super Admin password when it has been accidentally overwritten
 * by adding a second identity (e.g., registering as agent).
 * 
 * Usage:
 *   node utils/resetSuperAdminPassword.js
 */

async function resetSuperAdminPassword() {
    try {
        console.log('🔧 Starting Super Admin password reset...\n');

        // Find Super Admin by email - update this to match your email
        const superAdminEmail = 'hassamsaleem55@gmail.com';  // Change this if different
        const newPassword = 'Admin@123';

        const superAdmin = await Register.findOne({ email: superAdminEmail });

        if (!superAdmin) {
            console.error('❌ Super Admin not found with email:', superAdminEmail);
            console.log('Please update the email address in this script if it\'s different.');
            process.exit(1);
        }

        console.log('✓ Found user:', superAdmin.name);
        console.log('  Email:', superAdmin.email);
        console.log('  Current roles:', superAdmin.roles.length);

        // Hash the new password
        const salt = await bcrypt.genSalt(10);
        const hashedPassword = await bcrypt.hash(newPassword, salt);

        // Update the password
        superAdmin.password = hashedPassword;
        superAdmin.plainPassword = newPassword;
        superAdmin.isAutoGeneratedPassword = false;
        await superAdmin.save();

        console.log('\n✅ Password reset successful!');
        console.log('');
        console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
        console.log('  New Login Credentials');
        console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
        console.log('  Email:    ', superAdmin.email);
        console.log('  Password: ', newPassword);
        console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
        console.log('');
        console.log('You can now login to:');
        console.log('  • Admin Panel: http://localhost:5174');
        if (superAdmin.agencyCode) {
            console.log('  • Agent Portal: http://localhost:5173');
            console.log(`  • Agency Code: ${superAdmin.agencyCode}`);
        }
        console.log('');
        console.log('⚠️  IMPORTANT: Change this password after logging in!');
        console.log('');

    } catch (error) {
        console.error('❌ Password reset failed:', error);
        throw error;
    }
}

// Run reset if executed directly
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);
const isMainModule = process.argv[1] === __filename || process.argv[1].replace(/\\/g, '/').endsWith('resetSuperAdminPassword.js');

if (isMainModule) {
    dbConnect()
        .then(() => resetSuperAdminPassword())
        .then(() => {
            console.log('✅ Reset complete. Exiting...\n');
            process.exit(0);
        })
        .catch((error) => {
            console.error('❌ Reset failed:', error);
            process.exit(1);
        });
}

export default resetSuperAdminPassword;
