import mongoose from "mongoose";
import bcrypt from "bcrypt";

const RegisterSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
      trim: true
    },

    email: {
      type: String,
      required: true,
      lowercase: true,
      trim: true
    },

    phone: {
      type: String,
      required: function () {
        return !this.isGoogleAccount;
      }
    },

    address: {
      type: String,
      trim: true,
      default: ""
    },

    country: {
      type: String,
      trim: true,
      default: ""
    },

    city: {
      type: String,
      trim: true,
      default: ""
    },

    password: {
      type: String,
      required: function () {
        return !this.isGoogleAccount;
      },
      minlength: 6,
      select: false
    },

    plainPassword: {
      type: String,
      required: false
    },


    isAutoGeneratedPassword: {
      type: Boolean,
      default: true
    },

    // Portal-specific OTP fields for identity separation
    agentOTP: {
      type: String,
      select: false
    },

    agentOTPExpiry: {
      type: Date,
      select: false
    },

    adminOTP: {
      type: String,
      select: false
    },

    adminOTPExpiry: {
      type: Date,
      select: false
    },

    roles: [{
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Role',
      required: false
    }],

    companyName: {
      type: String
    },

    consultant: {
      type: String,
      trim: true,
      default: ""
    },

    logo: {
      type: String,
      trim: true,
      default: ""
    },

    agencyCode: {
      type: String,
      unique: true,
      sparse: true
    },

    status: {
      type: String,
      enum: ["Active", "Inactive", "Suspended"],
      default: "Active"
    },

    // Separate agent status for agent role workflow management
    agentStatus: {
      type: String,
      enum: ["Active", "Inactive", "Suspended", "Pending"],
      default: "Pending"
    },

    marginType: {
      type: String,
      enum: ["Percentage", "Amount"],
      default: "Percentage"
    },

    flightMarginPercent: {
      type: Number,
      default: 0
    },

    flightMarginAmount: {
      type: Number,
      default: 0
    },

    creditAmount: {
      type: Number,
      default: 0
    },

    registeredFrom: {
      ipAddress: {
        type: String,
        default: ""
      },
      userAgent: {
        type: String,
        default: ""
      }
    },

    lastLogin: {
      type: Date
    },

    activatedBy: {
      type: String,
      default: ""
    },

    activatedAt: {
      type: Date
    },

    deactivatedBy: {
      type: String,
      default: ""
    },

    deactivatedAt: {
      type: Date
    },

    // Agent-specific activation tracking
    agentActivatedBy: {
      type: String,
      default: ""
    },

    agentActivatedAt: {
      type: Date
    },

    agentDeactivatedBy: {
      type: String,
      default: ""
    },

    agentDeactivatedAt: {
      type: Date
    },

    isGoogleAccount: {
      type: Boolean,
      default: false
    },
  },
  { timestamps: true }
);

/* ===========================
   PASSWORD HASHING
=========================== */
RegisterSchema.pre("save", async function () {
  if (!this.isModified("password")) return;

  const salt = await bcrypt.genSalt(10);
  this.password = await bcrypt.hash(this.password, salt);
});

/* ===========================
   PASSWORD COMPARE METHOD
=========================== */
RegisterSchema.methods.comparePassword = async function (enteredPassword) {
  return await bcrypt.compare(enteredPassword, this.password);
};

/* ===========================
   INDEXES
=========================== */
// Unique email - one user per email with multiple roles
RegisterSchema.index({ email: 1 }, { unique: true });
RegisterSchema.index({ roles: 1 });

export default mongoose.model("Register", RegisterSchema);
